agentName: npm
agentType: integration
title: 'Network security prerequisites'
metaDescription: 'Network monitoring prerequisites'
introFilePath: 'src/install/npm/intro.mdx'
appInfo: 
  - optionType: dropdown1
    label: ''
    placeholder: 'Select your region'
    options: 
      - value: 'us'
        displayName: 'US'
        recommendedGuided: true
      - value: 'usFedramp'
        displayName: 'US Fedramp'
      - value: 'eu'
        displayName: 'EU'
  - optionType: dropdown2
    label: ''
    placeholder: 'Select your installation method'
    options: 
      - value: 'docker'
        displayName: ''
        recommendedGuided: true
        logo: 'docker'
      - value: 'linux'
        displayName: 'Linux'
        logo: 'linux'

steps:
  - filePath: 'src/install/npm/appInfo.mdx'
  - filePath: 'src/install/npm/docker-us.mdx'
    overrides: 
    - filePath: 'src/install/npm/docker-eu.mdx'
      selectedOptions: 
        - optionType: dropdown1
          options: 
            - value: 'eu'
        - optionType: dropdown2
          options: 
            - value: 'docker'

