name: Update Attribute Dictionary JSON

on:
  # TODO: This will eventually become a daily cron job
  workflow_dispatch:
  #   schedule:
  #     - cron: '0 17 * * 2' # 9AM PST (5PM UTC) on Tuesday mornings
  pull_request:
    branches:
      - clark/attribute-dictionary-json-action

env:
  API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
  BOT_NAME: nr-opensource-bot
  BOT_EMAIL: opensource+bot@newrelic.com

jobs:
  update-json:
    name: Update JSON
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Fetch Attribute Dictionary Data
        id: fetch-attribute-dictionary
        run: yarn update-attribute-dictionary-json

      - name: Commit changes
        id: commit-changes
        run: |
          git config --local user.email "${{ env.BOT_EMAIL }}"
          git config --local user.name "${{ env.BOT_NAME }}"
          git add attribute-dictionary.json
          git commit -m 'chore: Update Attribute Dictionary JSON'
          echo "commit=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        id: create-pr
        if: steps.fetch-attribute-dictionary.outputs.updateAttributeDictionary === true
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.DEVEX_OPENSOURCE_BOT_TOKEN }}
          title: Update Attribute Dictionary JSON - ${{ steps.date.outputs.date }}
          branch: update-attribute-dictionary-json
          body: ''
          base: clark/attribute-dictionary-json-action
          delete-branch: true
